// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        (unknown)
// source: proto/v1/messages.proto

package proto_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileStatus int32

const (
	FileStatus_FILE_STATUS_UNSPECIFIED FileStatus = 0
	FileStatus_FILE_STATUS_SCANNED     FileStatus = 1
	FileStatus_FILE_STATUS_CREATED     FileStatus = 2
	FileStatus_FILE_STATUS_UPDATED     FileStatus = 3
	FileStatus_FILE_STATUS_REMOVED     FileStatus = 4
)

// Enum value maps for FileStatus.
var (
	FileStatus_name = map[int32]string{
		0: "FILE_STATUS_UNSPECIFIED",
		1: "FILE_STATUS_SCANNED",
		2: "FILE_STATUS_CREATED",
		3: "FILE_STATUS_UPDATED",
		4: "FILE_STATUS_REMOVED",
	}
	FileStatus_value = map[string]int32{
		"FILE_STATUS_UNSPECIFIED": 0,
		"FILE_STATUS_SCANNED":     1,
		"FILE_STATUS_CREATED":     2,
		"FILE_STATUS_UPDATED":     3,
		"FILE_STATUS_REMOVED":     4,
	}
)

func (x FileStatus) Enum() *FileStatus {
	p := new(FileStatus)
	*p = x
	return p
}

func (x FileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_messages_proto_enumTypes[0].Descriptor()
}

func (FileStatus) Type() protoreflect.EnumType {
	return &file_proto_v1_messages_proto_enumTypes[0]
}

func (x FileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileStatus.Descriptor instead.
func (FileStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_messages_proto_rawDescGZIP(), []int{0}
}

type FileAction int32

const (
	FileAction_FILE_ACTION_UNSPECIFIED FileAction = 0
	FileAction_FILE_ACTION_UPLOAD      FileAction = 1
	FileAction_FILE_ACTION_DOWNLOAD    FileAction = 2
	FileAction_FILE_ACTION_REMOVE      FileAction = 3
	FileAction_FILE_ACTION_CREATE      FileAction = 4
)

// Enum value maps for FileAction.
var (
	FileAction_name = map[int32]string{
		0: "FILE_ACTION_UNSPECIFIED",
		1: "FILE_ACTION_UPLOAD",
		2: "FILE_ACTION_DOWNLOAD",
		3: "FILE_ACTION_REMOVE",
		4: "FILE_ACTION_CREATE",
	}
	FileAction_value = map[string]int32{
		"FILE_ACTION_UNSPECIFIED": 0,
		"FILE_ACTION_UPLOAD":      1,
		"FILE_ACTION_DOWNLOAD":    2,
		"FILE_ACTION_REMOVE":      3,
		"FILE_ACTION_CREATE":      4,
	}
)

func (x FileAction) Enum() *FileAction {
	p := new(FileAction)
	*p = x
	return p
}

func (x FileAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_messages_proto_enumTypes[1].Descriptor()
}

func (FileAction) Type() protoreflect.EnumType {
	return &file_proto_v1_messages_proto_enumTypes[1]
}

func (x FileAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileAction.Descriptor instead.
func (FileAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_messages_proto_rawDescGZIP(), []int{1}
}

type FileSyncInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Path      string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Status    FileStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=proto.v1.FileStatus" json:"status,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsDir     bool                   `protobuf:"varint,5,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
}

func (x *FileSyncInfo) Reset() {
	*x = FileSyncInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileSyncInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSyncInfo) ProtoMessage() {}

func (x *FileSyncInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSyncInfo.ProtoReflect.Descriptor instead.
func (*FileSyncInfo) Descriptor() ([]byte, []int) {
	return file_proto_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *FileSyncInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FileSyncInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileSyncInfo) GetStatus() FileStatus {
	if x != nil {
		return x.Status
	}
	return FileStatus_FILE_STATUS_UNSPECIFIED
}

func (x *FileSyncInfo) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *FileSyncInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

type CacheDump struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files [][]byte `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *CacheDump) Reset() {
	*x = CacheDump{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheDump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheDump) ProtoMessage() {}

func (x *CacheDump) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheDump.ProtoReflect.Descriptor instead.
func (*CacheDump) Descriptor() ([]byte, []int) {
	return file_proto_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CacheDump) GetFiles() [][]byte {
	if x != nil {
		return x.Files
	}
	return nil
}

type ServerFileSyncInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Path      string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsDir     bool                   `protobuf:"varint,4,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Action    FileAction             `protobuf:"varint,5,opt,name=action,proto3,enum=proto.v1.FileAction" json:"action,omitempty"`
}

func (x *ServerFileSyncInfo) Reset() {
	*x = ServerFileSyncInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerFileSyncInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFileSyncInfo) ProtoMessage() {}

func (x *ServerFileSyncInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFileSyncInfo.ProtoReflect.Descriptor instead.
func (*ServerFileSyncInfo) Descriptor() ([]byte, []int) {
	return file_proto_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ServerFileSyncInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ServerFileSyncInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ServerFileSyncInfo) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ServerFileSyncInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *ServerFileSyncInfo) GetAction() FileAction {
	if x != nil {
		return x.Action
	}
	return FileAction_FILE_ACTION_UNSPECIFIED
}

type FilePart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Index  uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Length uint64 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	Data   []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FilePart) Reset() {
	*x = FilePart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilePart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePart) ProtoMessage() {}

func (x *FilePart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePart.ProtoReflect.Descriptor instead.
func (*FilePart) Descriptor() ([]byte, []int) {
	return file_proto_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *FilePart) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FilePart) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FilePart) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *FilePart) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_v1_messages_proto protoreflect.FileDescriptor

var file_proto_v1_messages_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb3, 0x01, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x6e,
	0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x2c, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x44, 0x69, 0x72, 0x22, 0x21, 0x0a, 0x09, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x44, 0x75, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0xb9, 0x01,
	0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x79, 0x6e, 0x63,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x44, 0x69, 0x72, 0x12, 0x2c, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x60, 0x0a, 0x08, 0x46, 0x69, 0x6c,
	0x65, 0x50, 0x61, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x8d, 0x01, 0x0a, 0x0a,
	0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x17, 0x46, 0x49,
	0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x46, 0x49, 0x4c, 0x45, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x43, 0x41, 0x4e, 0x4e, 0x45, 0x44, 0x10, 0x01,
	0x12, 0x17, 0x0a, 0x13, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x46, 0x49, 0x4c,
	0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x44,
	0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x44, 0x10, 0x04, 0x2a, 0x8b, 0x01, 0x0a, 0x0a,
	0x46, 0x69, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x17, 0x46, 0x49,
	0x4c, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x46, 0x49, 0x4c, 0x45, 0x5f,
	0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44, 0x10, 0x01, 0x12,
	0x18, 0x0a, 0x14, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x44,
	0x4f, 0x57, 0x4e, 0x4c, 0x4f, 0x41, 0x44, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x46, 0x49, 0x4c,
	0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x10,
	0x03, 0x12, 0x16, 0x0a, 0x12, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x04, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v1_messages_proto_rawDescOnce sync.Once
	file_proto_v1_messages_proto_rawDescData = file_proto_v1_messages_proto_rawDesc
)

func file_proto_v1_messages_proto_rawDescGZIP() []byte {
	file_proto_v1_messages_proto_rawDescOnce.Do(func() {
		file_proto_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v1_messages_proto_rawDescData)
	})
	return file_proto_v1_messages_proto_rawDescData
}

var file_proto_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_v1_messages_proto_goTypes = []interface{}{
	(FileStatus)(0),               // 0: proto.v1.FileStatus
	(FileAction)(0),               // 1: proto.v1.FileAction
	(*FileSyncInfo)(nil),          // 2: proto.v1.FileSyncInfo
	(*CacheDump)(nil),             // 3: proto.v1.CacheDump
	(*ServerFileSyncInfo)(nil),    // 4: proto.v1.ServerFileSyncInfo
	(*FilePart)(nil),              // 5: proto.v1.FilePart
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_v1_messages_proto_depIdxs = []int32{
	0, // 0: proto.v1.FileSyncInfo.status:type_name -> proto.v1.FileStatus
	6, // 1: proto.v1.FileSyncInfo.timestamp:type_name -> google.protobuf.Timestamp
	6, // 2: proto.v1.ServerFileSyncInfo.timestamp:type_name -> google.protobuf.Timestamp
	1, // 3: proto.v1.ServerFileSyncInfo.action:type_name -> proto.v1.FileAction
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_v1_messages_proto_init() }
func file_proto_v1_messages_proto_init() {
	if File_proto_v1_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_v1_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileSyncInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheDump); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerFileSyncInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilePart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v1_messages_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_messages_proto_goTypes,
		DependencyIndexes: file_proto_v1_messages_proto_depIdxs,
		EnumInfos:         file_proto_v1_messages_proto_enumTypes,
		MessageInfos:      file_proto_v1_messages_proto_msgTypes,
	}.Build()
	File_proto_v1_messages_proto = out.File
	file_proto_v1_messages_proto_rawDesc = nil
	file_proto_v1_messages_proto_goTypes = nil
	file_proto_v1_messages_proto_depIdxs = nil
}
