// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        (unknown)
// source: proto/v1/responses.proto

package proto_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileTransferStatus int32

const (
	FileTransferStatus_FILE_TRANSFER_STATUS_UNSPECIFIED FileTransferStatus = 0
	FileTransferStatus_FILE_TRANSFER_STATUS_OK          FileTransferStatus = 1
	FileTransferStatus_FILE_TRANSFER_STATUS_FAILED      FileTransferStatus = 2
)

// Enum value maps for FileTransferStatus.
var (
	FileTransferStatus_name = map[int32]string{
		0: "FILE_TRANSFER_STATUS_UNSPECIFIED",
		1: "FILE_TRANSFER_STATUS_OK",
		2: "FILE_TRANSFER_STATUS_FAILED",
	}
	FileTransferStatus_value = map[string]int32{
		"FILE_TRANSFER_STATUS_UNSPECIFIED": 0,
		"FILE_TRANSFER_STATUS_OK":          1,
		"FILE_TRANSFER_STATUS_FAILED":      2,
	}
)

func (x FileTransferStatus) Enum() *FileTransferStatus {
	p := new(FileTransferStatus)
	*p = x
	return p
}

func (x FileTransferStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileTransferStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_responses_proto_enumTypes[0].Descriptor()
}

func (FileTransferStatus) Type() protoreflect.EnumType {
	return &file_proto_v1_responses_proto_enumTypes[0]
}

func (x FileTransferStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileTransferStatus.Descriptor instead.
func (FileTransferStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_responses_proto_rawDescGZIP(), []int{0}
}

type StartSynchronizationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []*ServerFileSyncInfo `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *StartSynchronizationResponse) Reset() {
	*x = StartSynchronizationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_responses_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartSynchronizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSynchronizationResponse) ProtoMessage() {}

func (x *StartSynchronizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_responses_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSynchronizationResponse.ProtoReflect.Descriptor instead.
func (*StartSynchronizationResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_responses_proto_rawDescGZIP(), []int{0}
}

func (x *StartSynchronizationResponse) GetFiles() []*ServerFileSyncInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type FinishSynchronizationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinishSynchronizationResponse) Reset() {
	*x = FinishSynchronizationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_responses_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishSynchronizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishSynchronizationResponse) ProtoMessage() {}

func (x *FinishSynchronizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_responses_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishSynchronizationResponse.ProtoReflect.Descriptor instead.
func (*FinishSynchronizationResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_responses_proto_rawDescGZIP(), []int{1}
}

type UploadFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status FileTransferStatus `protobuf:"varint,1,opt,name=status,proto3,enum=proto.v1.FileTransferStatus" json:"status,omitempty"`
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_responses_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_responses_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_responses_proto_rawDescGZIP(), []int{2}
}

func (x *UploadFileResponse) GetStatus() FileTransferStatus {
	if x != nil {
		return x.Status
	}
	return FileTransferStatus_FILE_TRANSFER_STATUS_UNSPECIFIED
}

type DownloadFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path        string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Index       uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Length      uint64 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	Data        []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	TotalParts  uint64 `protobuf:"varint,5,opt,name=total_parts,json=totalParts,proto3" json:"total_parts,omitempty"`
	TotalLength uint64 `protobuf:"varint,6,opt,name=total_length,json=totalLength,proto3" json:"total_length,omitempty"`
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_responses_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_responses_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_responses_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadFileResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DownloadFileResponse) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DownloadFileResponse) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *DownloadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownloadFileResponse) GetTotalParts() uint64 {
	if x != nil {
		return x.TotalParts
	}
	return 0
}

func (x *DownloadFileResponse) GetTotalLength() uint64 {
	if x != nil {
		return x.TotalLength
	}
	return 0
}

var File_proto_v1_responses_proto protoreflect.FileDescriptor

var file_proto_v1_responses_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a,
	0x1c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a,
	0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x69,
	0x6c, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x22, 0x1f, 0x0a, 0x1d, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x53, 0x79, 0x6e, 0x63, 0x68,
	0x72, 0x6f, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x4a, 0x0a, 0x12, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xb0,
	0x01, 0x0a, 0x14, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x74, 0x73, 0x12, 0x21,
	0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x2a, 0x78, 0x0a, 0x12, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x20, 0x46, 0x49, 0x4c, 0x45, 0x5f,
	0x54, 0x52, 0x41, 0x4e, 0x53, 0x46, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1b, 0x0a,
	0x17, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x46, 0x45, 0x52, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x46, 0x49,
	0x4c, 0x45, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x46, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x42, 0x0a, 0x5a, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v1_responses_proto_rawDescOnce sync.Once
	file_proto_v1_responses_proto_rawDescData = file_proto_v1_responses_proto_rawDesc
)

func file_proto_v1_responses_proto_rawDescGZIP() []byte {
	file_proto_v1_responses_proto_rawDescOnce.Do(func() {
		file_proto_v1_responses_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v1_responses_proto_rawDescData)
	})
	return file_proto_v1_responses_proto_rawDescData
}

var file_proto_v1_responses_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v1_responses_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_v1_responses_proto_goTypes = []interface{}{
	(FileTransferStatus)(0),               // 0: proto.v1.FileTransferStatus
	(*StartSynchronizationResponse)(nil),  // 1: proto.v1.StartSynchronizationResponse
	(*FinishSynchronizationResponse)(nil), // 2: proto.v1.FinishSynchronizationResponse
	(*UploadFileResponse)(nil),            // 3: proto.v1.UploadFileResponse
	(*DownloadFileResponse)(nil),          // 4: proto.v1.DownloadFileResponse
	(*ServerFileSyncInfo)(nil),            // 5: proto.v1.ServerFileSyncInfo
}
var file_proto_v1_responses_proto_depIdxs = []int32{
	5, // 0: proto.v1.StartSynchronizationResponse.files:type_name -> proto.v1.ServerFileSyncInfo
	0, // 1: proto.v1.UploadFileResponse.status:type_name -> proto.v1.FileTransferStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_responses_proto_init() }
func file_proto_v1_responses_proto_init() {
	if File_proto_v1_responses_proto != nil {
		return
	}
	file_proto_v1_messages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_v1_responses_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartSynchronizationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_responses_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishSynchronizationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_responses_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_responses_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v1_responses_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_responses_proto_goTypes,
		DependencyIndexes: file_proto_v1_responses_proto_depIdxs,
		EnumInfos:         file_proto_v1_responses_proto_enumTypes,
		MessageInfos:      file_proto_v1_responses_proto_msgTypes,
	}.Build()
	File_proto_v1_responses_proto = out.File
	file_proto_v1_responses_proto_rawDesc = nil
	file_proto_v1_responses_proto_goTypes = nil
	file_proto_v1_responses_proto_depIdxs = nil
}
